// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvR94VBoO6Kt4dxndIstStWGHd3mxgh1U',
    appId: '1:849074430946:web:0421510e5d7a0200520fbb',
    messagingSenderId: '849074430946',
    projectId: 'taxiapp-b0cd7',
    authDomain: 'taxiapp-b0cd7.firebaseapp.com',
    storageBucket: 'taxiapp-b0cd7.firebasestorage.app',
    measurementId: 'G-HTD081E016',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_blq9cz8aXy7EqC0MO_yQITmIbHKQrYw',
    appId: '1:849074430946:android:c92cff789f0455db520fbb',
    messagingSenderId: '849074430946',
    projectId: 'taxiapp-b0cd7',
    storageBucket: 'taxiapp-b0cd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOU2cInSl9D4ZAq7jsOLXT_Rbu8IwTFqM',
    appId: '1:849074430946:ios:afdb024cdceb3db2520fbb',
    messagingSenderId: '849074430946',
    projectId: 'taxiapp-b0cd7',
    storageBucket: 'taxiapp-b0cd7.firebasestorage.app',
    iosBundleId: 'com.example.riderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOU2cInSl9D4ZAq7jsOLXT_Rbu8IwTFqM',
    appId: '1:849074430946:ios:afdb024cdceb3db2520fbb',
    messagingSenderId: '849074430946',
    projectId: 'taxiapp-b0cd7',
    storageBucket: 'taxiapp-b0cd7.firebasestorage.app',
    iosBundleId: 'com.example.riderapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvR94VBoO6Kt4dxndIstStWGHd3mxgh1U',
    appId: '1:849074430946:web:dee862f9e77341cd520fbb',
    messagingSenderId: '849074430946',
    projectId: 'taxiapp-b0cd7',
    authDomain: 'taxiapp-b0cd7.firebaseapp.com',
    storageBucket: 'taxiapp-b0cd7.firebasestorage.app',
    measurementId: 'G-T3SVZ9QKL4',
  );
}
